#pragma once

namespace map_reduce
{

enum class ErrorCode
{
  OK = 0,
  SOCKET_SERVER_CREATE_FAIL,
  SOCKET_CLIENT_CREATE_FAIL,
  SOCKET_BIND_FAIL,
  SOCKET_LISTEN_FAIL,
  SOCKET_ACCEPT_FAIL,
  SOCKET_READ_SERVER_FAIL,
  SOCKET_READ_CLIENT_FAIL,
  SOCKET_WRITE_SERVER_FAIL,
  SOCKET_WRITE_CLIENT_FAIL,
  SOCKET_CONNECT_FAIL,
  DLOPEN_FAIL,
  DLSYM_FAIL,
  TASK_INTERRUPTED
};

void logger(ErrorCode err);

}
